apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: k8sjeeves
  name: k8sjeeves
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8sjeeves-read
subjects:
- kind: ServiceAccount
  name: default
  namespace: k8sjeeves